<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:macro name="diffbot" params="prefix">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="12.0" /> 
    <xacro:property name="base_width" value="0.60" />
    <xacro:property name="base_length" value="0.36" />
    <xacro:property name="base_height" value="0.125" />
    <xacro:property name="drive_sprocket_mass" value="0.5" /> 
    <xacro:property name="drive_sprocket_width" value="0.06" />
    <xacro:property name="drive_sprocket_radius" value="0.073" />
    <xacro:property name="z_offset" value="-${base_height/2}" /> 


    <link name="base_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_width} ${base_length} ${base_height}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_width} ${base_length} ${base_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia
          ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" 
          iyz="0.0"
          izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>
    


    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <joint name="${prefix}left_track_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_drive_sprocket"/>
      <origin xyz="-${base_width / 2.0 + drive_sprocket_radius / 3.0} -${base_length / 2.0 + 0.05} ${base_height / 2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>
    <link name="${prefix}left_drive_sprocket">
      <collision>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
      <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
      </geometry>
    <surface>
    <friction>
      <ode>
        <mu>1.0</mu>      
        <mu2>0.5</mu2>    
        <slip1>0.0</slip1>  
        <slip2>0.0</slip2>   
      </ode>
    </friction>
            <contact>
              <ode>
                <soft_cfm>0.0</soft_cfm>
                <soft_erp>0.2</soft_erp>
                <kp>1e+13</kp>
                <kd>1.0</kd>
                <max_vel>0.01</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
        </surface>
        <geometry>
          <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${drive_sprocket_mass}"/>
        <inertia
          ixx="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          iyz="0.0"
          izz="${drive_sprocket_mass / 2.0 * drive_sprocket_radius*drive_sprocket_radius}"/>
      </inertial>
    </link>

    <joint name="${prefix}right_track_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_drive_sprocket"/>
      <origin xyz="-${base_width / 2.0 + drive_sprocket_radius / 3.0} ${base_length / 2.0 + 0.05} ${base_height / 2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>
    <link name="${prefix}right_drive_sprocket">
      <collision>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
      <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
      </geometry>
    <surface>
    <friction>
      <ode>
        <mu>0.6</mu>        
        <mu2>0.3</mu2>      
        <slip1>0.0</slip1>   
        <slip2>0.0</slip2>   
      </ode>
    </friction>
            <contact>
              <ode>
                <soft_cfm>0.0</soft_cfm>
                <soft_erp>0.2</soft_erp>
                <kp>1e+13</kp>
                <kd>1.0</kd>
                <max_vel>0.01</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
        </surface>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${drive_sprocket_mass}"/>
        <inertia
          ixx="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          iyz="0.0"
          izz="${drive_sprocket_mass / 2.0 * drive_sprocket_radius*drive_sprocket_radius}"/>
      </inertial>
    </link>


    <joint name="${prefix}front_right_track_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_right_idler"/>
      <origin xyz="${base_width / 2.0 + drive_sprocket_radius / 3.0} ${base_length / 2.0 + 0.05} ${base_height / 2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <mimic joint="${prefix}left_track_joint" multiplier="1.0"/>
    </joint>
    <link name="${prefix}front_right_idler">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
      <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
      </geometry>
    <surface>
    <friction>
      <ode>
        <mu>0.6</mu>        
        <mu2>0.3</mu2>      
        <slip1>0.0</slip1>   
        <slip2>0.0</slip2>   
      </ode>
    </friction>
            <contact>
              <ode>
                <soft_cfm>0.0</soft_cfm>
                <soft_erp>0.2</soft_erp>
                <kp>1e+13</kp>
                <kd>1.0</kd>
                <max_vel>0.01</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
        </surface>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${drive_sprocket_mass}"/>
        <inertia
          ixx="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          iyz="0.0"
          izz="${drive_sprocket_mass / 2.0 * drive_sprocket_radius*drive_sprocket_radius}"/>
      </inertial>
    </link>


    <joint name="${prefix}front_left_track_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_left_idler"/>
      <origin xyz="${base_width / 2.0 + drive_sprocket_radius / 3.0} -${base_length / 2.0 + 0.05} ${base_height / 2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <mimic joint="${prefix}left_track_joint" multiplier="1.0"/>
    </joint>
    <link name="${prefix}front_left_idler">
      <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
      <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
      </geometry>
    <surface>
    <friction>
      <ode>
        <mu>0.6</mu>       
        <mu2>0.3</mu2>      
        <slip1>0.0</slip1>  
        <slip2>0.0</slip2>   
      </ode>
    </friction>
            <contact>
              <ode>
                <soft_cfm>0.0</soft_cfm>
                <soft_erp>0.2</soft_erp>
                <kp>1e+13</kp>
                <kd>1.0</kd>
                <max_vel>0.01</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
        </surface>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${drive_sprocket_width}" radius="${drive_sprocket_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${drive_sprocket_mass}"/>
        <inertia
          ixx="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${drive_sprocket_mass / 12.0 * (3*drive_sprocket_radius*drive_sprocket_radius + drive_sprocket_width*drive_sprocket_width)}" 
          iyz="0.0"
          izz="${drive_sprocket_mass / 2.0 * drive_sprocket_radius*drive_sprocket_radius}"/>
      </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
  <parent link="base_link"/>
  <child link="lidar"/>
  <origin xyz="0.3 0 0.225" rpy="0 0 ${PI}"/>  
</joint>
<link name="lidar">
  <visual>
    <geometry>
      <cylinder length="0.02" radius="0.02"/>
    </geometry>
    <material name="red"/>
  </visual>
</link>

  </xacro:macro>
</robot>